apiVersion: v1
kind: Service
metadata:
  name: sd-webui
  namespace: stable-diffusion
spec:
  type: NodePort
  selector:
    name: sd-webui
  ports:
    - name: http
      protocol: TCP
      port: 7860
      targetPort: 7860
      nodePort: 30860